### ISSUE TITLE
Show configured coverage threshold in output

### ISSUE THREAD

**Issue by domudall** [ConnectedVentures/fresh8-gb-ci#2]
It'd be useful to know the threshold when coverage fails, at present only shows you coverage of specific parts of the codebase.

**Comment by jimah** [comment]
This has been added in https://github.com/ConnectedVentures/fresh8-gb-ci/pull/4. Currently awaiting PR.

**Comment by jimah** [comment]
https://github.com/ConnectedVentures/fresh8-gb-ci/pull/4 has now been merged into master.

Closing the issue.
